apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: 656534314120.dkr.ecr.ap-southeast-1.amazonaws.com/mlzoomcamp-images:zoomcamp-10-gateway-002
        resources:
          limits:
            memory: "512Mi"
            cpu: "0.5"
        ports:
        - containerPort: 9696
        env:
        - name: TF_SERVING_HOST
          value: tf-serving-clothing-model.default.svc.cluster.local:8500